{% set version = "0.15.0" %}

package:
  name: tensorflow-hub
  version: {{ version }}

source:
  url: https://github.com/tensorflow/hub/archive/v{{ version }}.tar.gz
  sha256: 8a152babfe6da400b9c59782cc8422c22b3219ffecf1e23a4ee8f49e3cd3d34d

build:
  number: 0
  # This is a noarch: python package, it contains no compiled code but a
  # compiler is required to convert protocol buffer definitions.
  noarch: python
  ignore_run_exports:
    - libgcc-ng
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel >=0.24
    - setuptools
    - wheel
  host:
    - python >=3.6
    - pip
  run:
    # The build has only been tested on linux-64
    - __linux
    - python >=3.6
    - numpy >=1.12.0
    - protobuf >=3.19.6
    - tensorflow >=1.14.0

test:
  imports:
    - tensorflow_hub

about:
  home: https://www.tensorflow.org/hub/
  license: Apache-2.0
  license_file: LICENSE
  summary: A library for transfer learning by reusing parts of TensorFlow models.

extra:
  recipe-maintainers:
    - ocefpaf
