{% set version = "0.16.1" %}

package:
  name: tensorflow-hub
  version: {{ version }}

source:
  url: https://pypi.org/packages/py2.py3/t/tensorflow-hub/tensorflow_hub-{{ version }}-py2.py3-none-any.whl
  sha256: e10c184b3d08daeafada11ffea2dd46781725b6bef01fad1f74d6634ad05311f

build:
  number: 3
  noarch: python
  script: {{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation tensorflow_hub-{{ version }}-py2.py3-none-any.whl

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - numpy >=1.12.0
    - protobuf >=3.19.6
    - tf-keras >=2.14.1

test:
  requires:
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - tensorflow_hub

about:
  home: https://pypi.org/project/tensorflow-hub/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A library for transfer learning by reusing parts of TensorFlow models.
  dev_url: https://github.com/tensorflow/hub

extra:
  recipe-maintainers:
    - ocefpaf
    - ehfd
