{% set version = "0.4.0" %}

package:
  name: tensorflow-hub
  version: {{ version }}

source:
  url: https://pypi.io/packages/py2.py3/t/tensorflow_hub/tensorflow_hub-{{ version }}-py2.py3-none-any.whl
  sha256: 299967392aeda7032d6bd29b178f65a9bd8e43cfc550ea427fd37507711d5ec2

build:
  number: 0
  noarch: python
  # install using pip from the whl files on PyPI
  # b/c this uses bazel to build.
  script: python -m pip install --no-deps --ignore-installed tensorflow_hub-{{ version }}-py2.py3-none-any.whl

requirements:
  host:
    - python
    - pip
  run:
    - python
    - tensorflow

test:
  imports:
    # Skip the import test on Linux as wheel file require a more recent
    # version of GLIBC++ than the VM used to build and test package.
    - tensorflow_hub  # [not linux]

about:
  home: https://www.tensorflow.org/hub/
  license: Apache-2.0
  license_file: tensorflow_hub-{{ version }}.dist-info/LICENSE.txt
  summary: A library for transfer learning by reusing parts of TensorFlow models.

extra:
  recipe-maintainers:
    - ocefpaf
