{% set version = "0.16.1" %}

package:
  name: tensorflow-hub
  version: {{ version }}

source:
  url: https://github.com/tensorflow/hub/archive/v{{ version }}.tar.gz
  sha256: ce6abd3f1d39d42333b07c608ae022ac09a3f5984b297b21436c3389d7b77af5

build:
  number: 2
  # This is a noarch: python package, it contains no compiled code but a
  # compiler is required to convert protocol buffer definitions.
  noarch: python
  ignore_run_exports:
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - bazel >=6.5.0
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - numpy >=1.12.0
    - protobuf >=3.19.6
    - tf-keras >=2.14.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - tensorflow_hub

about:
  home: https://www.tensorflow.org/hub/
  license: Apache-2.0
  license_file: LICENSE
  summary: A library for transfer learning by reusing parts of TensorFlow models.

extra:
  recipe-maintainers:
    - ocefpaf
    - ehfd
