{% set version = "0.16.1" %}

package:
  name: tensorflow-hub
  version: {{ version }}

source:
  url: https://github.com/tensorflow/hub/archive/v{{ version }}.tar.gz
  sha256: ce6abd3f1d39d42333b07c608ae022ac09a3f5984b297b21436c3389d7b77af5

build:
  number: 1
  # This is a noarch: python package, it contains no compiled code but a
  # compiler is required to convert protocol buffer definitions.
  noarch: python
  ignore_run_exports:
    - libgcc-ng
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel >=0.24
    - setuptools
    - wheel
  host:
    - python >=3.6
    - pip
  run:
    # The build has only been tested on linux-64
    - __linux
    - python >=3.6
    - numpy >=1.12.0
    - protobuf >=3.19.6
    - tf-keras >=2.14.1

test:
  imports:
    - tensorflow_hub

about:
  home: https://www.tensorflow.org/hub/
  license: Apache-2.0
  license_file: LICENSE
  summary: A library for transfer learning by reusing parts of TensorFlow models.

extra:
  recipe-maintainers:
    - ocefpaf
